AssistantAPIKey: ''
AssistantID: ''
AssistantURL: ''
SpeechToTextAPIKey: ''
SpeechToTextListeningTime: 5
SpeechToTextURL: ''
TextToSpeechAPIKey: ''
TextToSpeechURL: ''
VisualRecognitionAPIKey: ''
VisualRecognitionURL: ''
camera: '0'
dialogflowv2_projectid: ''
distro: standalone
gassistant_proyectid: ''
ip: 192.168.1.10
language: italian
microphoneGain: '100'
servoSpeed: 100
startWith: develop
tokenAPIai: ''
volume: 75